# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\LFIPRSimulator.ui'
#
# Created: Sat May 05 08:25:33 2018
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_LFIPRSimulator(object):
    def setupUi(self, LFIPRSimulator):
        LFIPRSimulator.setObjectName(_fromUtf8("LFIPRSimulator"))
        LFIPRSimulator.resize(1258, 818)
        self.centralwidget = QtGui.QWidget(LFIPRSimulator)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.mplwidgetPower = MatplotlibWidget(self.centralwidget)
        self.mplwidgetPower.setObjectName(_fromUtf8("mplwidgetPower"))
        self.gridLayout_3.addWidget(self.mplwidgetPower, 0, 2, 1, 1)
        self.mplwidgetTemperature = MatplotlibWidget(self.centralwidget)
        self.mplwidgetTemperature.setObjectName(_fromUtf8("mplwidgetTemperature"))
        self.gridLayout_3.addWidget(self.mplwidgetTemperature, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Franklin Gothic Medium Cond"))
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setFrameShape(QtGui.QFrame.Box)
        self.label_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_7.setLineWidth(7)
        self.label_7.setTextFormat(QtCore.Qt.RichText)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setWordWrap(False)
        self.label_7.setIndent(0)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 1, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.splitter_7 = QtGui.QSplitter(self.groupBox_2)
        self.splitter_7.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_7.setObjectName(_fromUtf8("splitter_7"))
        self.doubleSpinBoxZ2 = QtGui.QDoubleSpinBox(self.splitter_7)
        self.doubleSpinBoxZ2.setEnabled(True)
        self.doubleSpinBoxZ2.setDecimals(2)
        self.doubleSpinBoxZ2.setMaximum(60.0)
        self.doubleSpinBoxZ2.setSingleStep(0.1)
        self.doubleSpinBoxZ2.setProperty("value", 20.0)
        self.doubleSpinBoxZ2.setObjectName(_fromUtf8("doubleSpinBoxZ2"))
        self.label_9 = QtGui.QLabel(self.splitter_7)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.splitter_7, 1, 1, 1, 1)
        self.splitter_6 = QtGui.QSplitter(self.groupBox_2)
        self.splitter_6.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_6.setObjectName(_fromUtf8("splitter_6"))
        self.doubleSpinBoxZ1 = QtGui.QDoubleSpinBox(self.splitter_6)
        self.doubleSpinBoxZ1.setWrapping(False)
        self.doubleSpinBoxZ1.setReadOnly(False)
        self.doubleSpinBoxZ1.setSpecialValueText(_fromUtf8(""))
        self.doubleSpinBoxZ1.setKeyboardTracking(True)
        self.doubleSpinBoxZ1.setDecimals(2)
        self.doubleSpinBoxZ1.setMaximum(60.0)
        self.doubleSpinBoxZ1.setSingleStep(0.1)
        self.doubleSpinBoxZ1.setProperty("value", 30.0)
        self.doubleSpinBoxZ1.setObjectName(_fromUtf8("doubleSpinBoxZ1"))
        self.label_10 = QtGui.QLabel(self.splitter_6)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.splitter_6, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.checkBoxPrecision = QtGui.QCheckBox(self.groupBox_2)
        self.checkBoxPrecision.setObjectName(_fromUtf8("checkBoxPrecision"))
        self.gridLayout_2.addWidget(self.checkBoxPrecision, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.groupBox_6 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.splitter_8 = QtGui.QSplitter(self.groupBox_6)
        self.splitter_8.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_8.setObjectName(_fromUtf8("splitter_8"))
        self.doubleSpinBoxNeutron = QtGui.QDoubleSpinBox(self.splitter_8)
        self.doubleSpinBoxNeutron.setObjectName(_fromUtf8("doubleSpinBoxNeutron"))
        self.label_6 = QtGui.QLabel(self.splitter_8)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_6.addWidget(self.splitter_8, 0, 0, 1, 1)
        self.pushButtonInitiate = QtGui.QPushButton(self.groupBox_6)
        self.pushButtonInitiate.setObjectName(_fromUtf8("pushButtonInitiate"))
        self.gridLayout_6.addWidget(self.pushButtonInitiate, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_6, 2, 1, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.dialV = QtGui.QDial(self.groupBox_3)
        self.dialV.setMaximum(500)
        self.dialV.setSingleStep(1)
        self.dialV.setObjectName(_fromUtf8("dialV"))
        self.verticalLayout_2.addWidget(self.dialV)
        self.splitter_5 = QtGui.QSplitter(self.groupBox_3)
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setObjectName(_fromUtf8("splitter_5"))
        self.labelV = QtGui.QLabel(self.splitter_5)
        self.labelV.setAlignment(QtCore.Qt.AlignCenter)
        self.labelV.setObjectName(_fromUtf8("labelV"))
        self.label = QtGui.QLabel(self.splitter_5)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.splitter_5)
        self.gridLayout.addWidget(self.groupBox_3, 0, 1, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_5 = QtGui.QLabel(self.groupBox_4)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_4.addWidget(self.label_5, 0, 0, 1, 1)
        self.horizontalSliderTfin = QtGui.QSlider(self.groupBox_4)
        self.horizontalSliderTfin.setMinimum(600)
        self.horizontalSliderTfin.setMaximum(990)
        self.horizontalSliderTfin.setProperty("value", 700)
        self.horizontalSliderTfin.setSliderPosition(700)
        self.horizontalSliderTfin.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderTfin.setObjectName(_fromUtf8("horizontalSliderTfin"))
        self.gridLayout_4.addWidget(self.horizontalSliderTfin, 1, 0, 1, 1)
        self.splitter = QtGui.QSplitter(self.groupBox_4)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.labelTfin = QtGui.QLabel(self.splitter)
        self.labelTfin.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelTfin.setObjectName(_fromUtf8("labelTfin"))
        self.label_12 = QtGui.QLabel(self.splitter)
        self.label_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_4.addWidget(self.splitter, 1, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.groupBox_4)
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_4.addWidget(self.label_13, 2, 0, 1, 1)
        self.horizontalSliderMdotf = QtGui.QSlider(self.groupBox_4)
        self.horizontalSliderMdotf.setMaximum(500)
        self.horizontalSliderMdotf.setProperty("value", 50)
        self.horizontalSliderMdotf.setSliderPosition(50)
        self.horizontalSliderMdotf.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderMdotf.setObjectName(_fromUtf8("horizontalSliderMdotf"))
        self.gridLayout_4.addWidget(self.horizontalSliderMdotf, 3, 0, 1, 1)
        self.splitter_2 = QtGui.QSplitter(self.groupBox_4)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.labelMdotf = QtGui.QLabel(self.splitter_2)
        self.labelMdotf.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelMdotf.setObjectName(_fromUtf8("labelMdotf"))
        self.label_14 = QtGui.QLabel(self.splitter_2)
        self.label_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_4.addWidget(self.splitter_2, 3, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_4, 1, 0, 1, 1)
        self.splitter_9 = QtGui.QSplitter(self.groupBox)
        self.splitter_9.setOrientation(QtCore.Qt.Vertical)
        self.splitter_9.setObjectName(_fromUtf8("splitter_9"))
        self.label_3 = QtGui.QLabel(self.splitter_9)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalSliderPlot = QtGui.QSlider(self.splitter_9)
        self.horizontalSliderPlot.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderPlot.setObjectName(_fromUtf8("horizontalSliderPlot"))
        self.gridLayout.addWidget(self.splitter_9, 2, 0, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_16 = QtGui.QLabel(self.groupBox_5)
        self.label_16.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_5.addWidget(self.label_16, 0, 0, 1, 1)
        self.horizontalSliderTcin = QtGui.QSlider(self.groupBox_5)
        self.horizontalSliderTcin.setMinimum(100)
        self.horizontalSliderTcin.setMaximum(990)
        self.horizontalSliderTcin.setProperty("value", 550)
        self.horizontalSliderTcin.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderTcin.setObjectName(_fromUtf8("horizontalSliderTcin"))
        self.gridLayout_5.addWidget(self.horizontalSliderTcin, 1, 0, 1, 1)
        self.splitter_3 = QtGui.QSplitter(self.groupBox_5)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.labelTcin = QtGui.QLabel(self.splitter_3)
        self.labelTcin.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelTcin.setObjectName(_fromUtf8("labelTcin"))
        self.label_18 = QtGui.QLabel(self.splitter_3)
        self.label_18.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_5.addWidget(self.splitter_3, 1, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.groupBox_5)
        self.label_19.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_5.addWidget(self.label_19, 2, 0, 1, 1)
        self.horizontalSliderMdotc = QtGui.QSlider(self.groupBox_5)
        self.horizontalSliderMdotc.setMaximum(500)
        self.horizontalSliderMdotc.setProperty("value", 100)
        self.horizontalSliderMdotc.setSliderPosition(100)
        self.horizontalSliderMdotc.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderMdotc.setObjectName(_fromUtf8("horizontalSliderMdotc"))
        self.gridLayout_5.addWidget(self.horizontalSliderMdotc, 3, 0, 1, 1)
        self.splitter_4 = QtGui.QSplitter(self.groupBox_5)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName(_fromUtf8("splitter_4"))
        self.labelMdotc = QtGui.QLabel(self.splitter_4)
        self.labelMdotc.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelMdotc.setObjectName(_fromUtf8("labelMdotc"))
        self.label_21 = QtGui.QLabel(self.splitter_4)
        self.label_21.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_5.addWidget(self.splitter_4, 3, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_5, 1, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 1, 1, 1, 1)
        self.mplwidgetReactivity = MatplotlibWidget(self.centralwidget)
        self.mplwidgetReactivity.setObjectName(_fromUtf8("mplwidgetReactivity"))
        self.gridLayout_3.addWidget(self.mplwidgetReactivity, 1, 2, 1, 1)
        self.graphicsView = QtGui.QGraphicsView(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.gridLayout_3.addWidget(self.graphicsView, 0, 0, 1, 1)
        LFIPRSimulator.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(LFIPRSimulator)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1258, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        LFIPRSimulator.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(LFIPRSimulator)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        LFIPRSimulator.setStatusBar(self.statusbar)
        self.actionFluks_Thermal = QtGui.QAction(LFIPRSimulator)
        self.actionFluks_Thermal.setObjectName(_fromUtf8("actionFluks_Thermal"))
        self.actionFluks_Neutron_Cepat = QtGui.QAction(LFIPRSimulator)
        self.actionFluks_Neutron_Cepat.setObjectName(_fromUtf8("actionFluks_Neutron_Cepat"))
        self.actionDaya_Reaktor = QtGui.QAction(LFIPRSimulator)
        self.actionDaya_Reaktor.setObjectName(_fromUtf8("actionDaya_Reaktor"))
        self.actionTemperatur_Bahan_Bakar = QtGui.QAction(LFIPRSimulator)
        self.actionTemperatur_Bahan_Bakar.setObjectName(_fromUtf8("actionTemperatur_Bahan_Bakar"))
        self.actionTemperatur_Pendingin = QtGui.QAction(LFIPRSimulator)
        self.actionTemperatur_Pendingin.setObjectName(_fromUtf8("actionTemperatur_Pendingin"))
        self.actionTemperatur_Pendingin_2 = QtGui.QAction(LFIPRSimulator)
        self.actionTemperatur_Pendingin_2.setObjectName(_fromUtf8("actionTemperatur_Pendingin_2"))
        self.actionTemperatur_Bahan_Bakar_2 = QtGui.QAction(LFIPRSimulator)
        self.actionTemperatur_Bahan_Bakar_2.setObjectName(_fromUtf8("actionTemperatur_Bahan_Bakar_2"))
        self.actionReaktivitas = QtGui.QAction(LFIPRSimulator)
        self.actionReaktivitas.setObjectName(_fromUtf8("actionReaktivitas"))
        self.actionPrekursor_Grup_1 = QtGui.QAction(LFIPRSimulator)
        self.actionPrekursor_Grup_1.setObjectName(_fromUtf8("actionPrekursor_Grup_1"))
        self.actionPrekursor_Grup_2 = QtGui.QAction(LFIPRSimulator)
        self.actionPrekursor_Grup_2.setObjectName(_fromUtf8("actionPrekursor_Grup_2"))
        self.actionPrekursor_Grup_3 = QtGui.QAction(LFIPRSimulator)
        self.actionPrekursor_Grup_3.setObjectName(_fromUtf8("actionPrekursor_Grup_3"))
        self.actionPrekursor_Grup_4 = QtGui.QAction(LFIPRSimulator)
        self.actionPrekursor_Grup_4.setObjectName(_fromUtf8("actionPrekursor_Grup_4"))
        self.actionPrekursor_Grup_5 = QtGui.QAction(LFIPRSimulator)
        self.actionPrekursor_Grup_5.setObjectName(_fromUtf8("actionPrekursor_Grup_5"))
        self.actionPrekursor_Grup_6 = QtGui.QAction(LFIPRSimulator)
        self.actionPrekursor_Grup_6.setObjectName(_fromUtf8("actionPrekursor_Grup_6"))
        self.actionKeluar = QtGui.QAction(LFIPRSimulator)
        self.actionKeluar.setObjectName(_fromUtf8("actionKeluar"))
        self.actionBuat_Dokumen = QtGui.QAction(LFIPRSimulator)
        self.actionBuat_Dokumen.setObjectName(_fromUtf8("actionBuat_Dokumen"))
        self.actionXenon_135 = QtGui.QAction(LFIPRSimulator)
        self.actionXenon_135.setObjectName(_fromUtf8("actionXenon_135"))
        self.actionSamarium_149_dan_Promethium_149 = QtGui.QAction(LFIPRSimulator)
        self.actionSamarium_149_dan_Promethium_149.setObjectName(_fromUtf8("actionSamarium_149_dan_Promethium_149"))
        self.menuView.addAction(self.actionXenon_135)
        self.menuView.addAction(self.actionSamarium_149_dan_Promethium_149)
        self.menuFile.addAction(self.actionKeluar)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(LFIPRSimulator)
        QtCore.QMetaObject.connectSlotsByName(LFIPRSimulator)

    def retranslateUi(self, LFIPRSimulator):
        LFIPRSimulator.setWindowTitle(_translate("LFIPRSimulator", "Simulator LFIPR", None))
        self.label_7.setText(_translate("LFIPRSimulator", "<html><head/><body><p align=\"center\"><span style=\" font-size:72pt; color:#00007f;\">LFIPR</span></p><p align=\"center\"><span style=\" font-size:11pt; font-style:italic; color:#aa0000;\">Liquid Fueled Isotope Production Reactor</span></p></body></html>", None))
        self.groupBox.setTitle(_translate("LFIPRSimulator", "Panel Kendali", None))
        self.groupBox_2.setTitle(_translate("LFIPRSimulator", "Batang Kendali", None))
        self.label_2.setText(_translate("LFIPRSimulator", "Sentral", None))
        self.label_9.setText(_translate("LFIPRSimulator", "cm", None))
        self.label_10.setText(_translate("LFIPRSimulator", "cm", None))
        self.label_4.setText(_translate("LFIPRSimulator", "Periferal", None))
        self.checkBoxPrecision.setText(_translate("LFIPRSimulator", "Presisi", None))
        self.groupBox_6.setTitle(_translate("LFIPRSimulator", "Neutron Eksternal", None))
        self.label_6.setText(_translate("LFIPRSimulator", "/(cm2.s)", None))
        self.pushButtonInitiate.setText(_translate("LFIPRSimulator", "Inisiasi", None))
        self.groupBox_3.setTitle(_translate("LFIPRSimulator", "Fraksi Void", None))
        self.labelV.setText(_translate("LFIPRSimulator", "0", None))
        self.label.setText(_translate("LFIPRSimulator", "%a", None))
        self.groupBox_4.setTitle(_translate("LFIPRSimulator", "Bahan Bakar", None))
        self.label_5.setText(_translate("LFIPRSimulator", "Temperatur Masuk", None))
        self.labelTfin.setText(_translate("LFIPRSimulator", "70", None))
        self.label_12.setText(_translate("LFIPRSimulator", "Celcius", None))
        self.label_13.setText(_translate("LFIPRSimulator", "Laju Massa", None))
        self.labelMdotf.setText(_translate("LFIPRSimulator", "5", None))
        self.label_14.setText(_translate("LFIPRSimulator", "kg/s", None))
        self.label_3.setText(_translate("LFIPRSimulator", "Plot Minimal", None))
        self.groupBox_5.setTitle(_translate("LFIPRSimulator", "Pendingin", None))
        self.label_16.setText(_translate("LFIPRSimulator", "Temperatur Masuk", None))
        self.labelTcin.setText(_translate("LFIPRSimulator", "55", None))
        self.label_18.setText(_translate("LFIPRSimulator", "Celcius", None))
        self.label_19.setText(_translate("LFIPRSimulator", "Laju Massa", None))
        self.labelMdotc.setText(_translate("LFIPRSimulator", "10", None))
        self.label_21.setText(_translate("LFIPRSimulator", "kg/s", None))
        self.menuView.setTitle(_translate("LFIPRSimulator", "View", None))
        self.menuFile.setTitle(_translate("LFIPRSimulator", "File", None))
        self.menuAbout.setTitle(_translate("LFIPRSimulator", "About", None))
        self.actionFluks_Thermal.setText(_translate("LFIPRSimulator", "Fluks Neutron Thermal", None))
        self.actionFluks_Neutron_Cepat.setText(_translate("LFIPRSimulator", "Fluks Neutron Cepat", None))
        self.actionDaya_Reaktor.setText(_translate("LFIPRSimulator", "Daya Reaktor", None))
        self.actionTemperatur_Bahan_Bakar.setText(_translate("LFIPRSimulator", "Temperatur Bahan Bakar", None))
        self.actionTemperatur_Pendingin.setText(_translate("LFIPRSimulator", "Temperatur Pendingin", None))
        self.actionTemperatur_Pendingin_2.setText(_translate("LFIPRSimulator", "Temperatur Pendingin", None))
        self.actionTemperatur_Bahan_Bakar_2.setText(_translate("LFIPRSimulator", "Temperatur Bahan Bakar", None))
        self.actionReaktivitas.setText(_translate("LFIPRSimulator", "Reaktivitas", None))
        self.actionPrekursor_Grup_1.setText(_translate("LFIPRSimulator", "Prekursor Grup 1", None))
        self.actionPrekursor_Grup_2.setText(_translate("LFIPRSimulator", "Prekursor Grup 2", None))
        self.actionPrekursor_Grup_3.setText(_translate("LFIPRSimulator", "Prekursor Grup 3", None))
        self.actionPrekursor_Grup_4.setText(_translate("LFIPRSimulator", "Prekursor Grup 4", None))
        self.actionPrekursor_Grup_5.setText(_translate("LFIPRSimulator", "Prekursor Grup 5", None))
        self.actionPrekursor_Grup_6.setText(_translate("LFIPRSimulator", "Prekursor Grup 6", None))
        self.actionKeluar.setText(_translate("LFIPRSimulator", "Keluar", None))
        self.actionBuat_Dokumen.setText(_translate("LFIPRSimulator", "Membuat Dokumen", None))
        self.actionXenon_135.setText(_translate("LFIPRSimulator", "Xenon-135 dan Iodine-135", None))
        self.actionSamarium_149_dan_Promethium_149.setText(_translate("LFIPRSimulator", "Samarium-149 dan Promethium-149", None))

from matplotlibwidget import MatplotlibWidget

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    LFIPRSimulator = QtGui.QMainWindow()
    ui = Ui_LFIPRSimulator()
    ui.setupUi(LFIPRSimulator)
    LFIPRSimulator.show()
    sys.exit(app.exec_())

